# Generated by Django 5.2.8 on 2025-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="숨김 여부"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                default="제목을 입력하세요.", max_length=20, verbose_name="제목"
            ),
        ),
    ]
